### ISSUE TITLE
Bound Must Be Positive

### ISSUE THREAD

**Issue by Seasonull** [stroyerr/AutoBroadcast#2]
Sorry if this isn't the right place or the right method for getting help with issues. New to github. Feel free to guide me.
Anyway, my problem is as stated below.

Running paper-1.18.1-198.jar

With no messages made, the plugin doesn't throw any errors in console.
Once I create a message the following appears in console every one second:

[16:01:17 WARN]: [[AutoBroadcast] ] Task #7 for AutoBroadcast v1.4 generated an exception
java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:322) ~[?:?]
        at net.stroyer.autobroadcast.Broadcast.Broadcast.broadcastMessage(Broadcast.java:48) ~[AutoBroadcast-1.4.jar:?]
        at net.stroyer.autobroadcast.Broadcast.BroadcastHandler.timerEvent(BroadcastHandler.java:32) ~[AutoBroadcast-1.4.jar:?]
        at net.stroyer.autobroadcast.Broadcast.BroadcastTimer$1.run(BroadcastTimer.java:39) ~[AutoBroadcast-1.4.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-198]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-198]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-198]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-198]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-198]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-198]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-198]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
![consoleerrorautobroadcast](https://user-images.githubusercontent.com/5394806/154819651-bcca89b6-6de3-44d2-aef3-aabf024a582c.png)

**Comment by stroyerr** [comment]
Hi, this appears to be a bug resulting from how I handle randomisation of messages.
Could you please give me a few details?
IE how many messages had you created when this bug occurred?

I'll fix this once I have fully debugged this and released a patch.
In the meantime, the none random broadcasts should cause you no issues.

**Comment by Seasonull** [comment]
Even when I make just one message and then put it on random this happens. I'll use the not random option for now. Thank you!

**Comment by stroyerr** [comment]
Thanks for letting me know, I'll work on a patch and update this thread once it's been released.

**Comment by stroyerr** [comment]
This bug has been fixed in the latest version (AutoBroadcast v1.4.2) and is now available for download at https://www.spigotmc.org/resources/autobroadcast.96264/

Thank you very much for the feedback!

If there is nothing further to this issue, this thread will be automatically closed when this issue hits 7 days old (27 Feb 2022 AEST).
